#!/usr/bin/env python
import argparse
import sys
import models
from models import *
import heapq
from collections import namedtuple
from span import *

parser = argparse.ArgumentParser(description='Simple phrase based decoder.')
parser.add_argument('-i', '--input', dest='input', default='data/input', help='File containing sentences to translate (default=data/input)')
parser.add_argument('-t', '--translation-model', dest='tm', default='data/tm', help='File containing translation model (default=data/tm)')
parser.add_argument('-s', '--stack-size', dest='s', default=30, type=int, help='Maximum stack size (default=1)')
parser.add_argument('-n', '--num_sentences', dest='num_sents', default=sys.maxint, type=int, help='Number of sentences to decode (default=no limit)')
parser.add_argument('-l', '--language-model', dest='lm', default='data/lm', help='File containing ARPA-format language model (default=data/lm)')
parser.add_argument('-v', '--verbose', dest='verbose', action='store_true', default=False,  help='Verbose mode (default=off)')
opts = parser.parse_args()

DISTORTION_PENALTY = 1.5
LOGPROB_OF_EMPTY_TRANSLATION = -20.0
EMPTY_TGT_PHRASE = phrase(english='MANAAL_WALEED', logprob=LOGPROB_OF_EMPTY_TRANSLATION)
DISTORTION_THRESHOLD = 4
MAX_PHRASE_OPTIONS = 10

tm = models.TM(opts.tm, MAX_PHRASE_OPTIONS)
lm = models.LM(opts.lm)
sys.stderr.write('Decoding %s...\n' % (opts.input,))
input_sents = [tuple(line.strip().split()) for line in open(opts.input).readlines()[:opts.num_sents]]

def baseline_decode(f):
    hypothesis = namedtuple('hypothesis', 'logprob, lm_state, predecessor, phrase')
    initial_hypothesis = hypothesis(0.0, lm.begin(), None, None)

    stacks = [{} for _ in f] + [{}]
    stacks[0][lm.begin()] = initial_hypothesis
    for i, stack in enumerate(stacks[:-1]):
        # extend the top s hypotheses in the current stack
        for h in heapq.nlargest(opts.s, stack.itervalues(), key=lambda h: h.logprob): # prune
            for j in xrange(i+1,len(f)+1):
                if f[i:j] in tm:
                    for phrase in tm[f[i:j]]:
                        logprob = h.logprob + phrase.logprob
                        lm_state = h.lm_state
                        for word in phrase.english.split():
                            (lm_state, word_logprob) = lm.score(lm_state, word)
                            logprob += word_logprob
                        logprob += lm.end(lm_state) if j == len(f) else 0.0
                        new_hypothesis = hypothesis(logprob, lm_state, h, phrase)
                        if lm_state not in stacks[j] or stacks[j][lm_state].logprob < logprob: # second case is recombination
                            stacks[j][lm_state] = new_hypothesis

    # find best translation by looking at the best scoring hypothesis
    # on the last stack
    winner = max(stacks[-1].itervalues(), key=lambda h: h.logprob)
    def extract_english_recursive(h):
        return '' if h.predecessor is None else '%s%s ' % (extract_english_recursive(h.predecessor), h.phrase.english)
    return winner
                    
hypothesis = namedtuple('hypothesis', 'logprob, heuristic_logprob, lm_state, bit_array, to_index, predecessor, phrase')
for f in input_sents:
    # The following code implements a DP monotone decoding
    # algorithm (one that doesn't permute the target phrases).
    # Hence all hypotheses in stacks[i] represent translations of 
    # the first i words of the input sentence.
    # HINT: Generalize this so that stacks[i] contains translations
    # of any i words (remember to keep track of which words those
    # are, and to estimate future costs)
    bit_array = [False for _ in f]
    initial_hypothesis = hypothesis(0.0, 0.0, lm.begin(), bit_array, 0, None, None)

    stacks = [{} for _ in f] + [{}]
    stacks[0][lm.begin()] = initial_hypothesis
    for i, stack in enumerate(stacks[:-1]):
        # extend the top s hypotheses in the current stack
        for h in heapq.nlargest(opts.s, stack.itervalues(), key=lambda h: h.heuristic_logprob): # prune
            free_spans = get_free_spans(h.bit_array)
            for span in free_spans:
                fromIndex = span[0]
                toIndex = span[-1]+1
                if toIndex - fromIndex == 1 and f[fromIndex:toIndex] not in tm:
                    tm[ tuple(f[fromIndex:toIndex]) ] = [EMPTY_TGT_PHRASE]
                if f[fromIndex:toIndex] in tm:
                    new_bit_array = list(h.bit_array)
                    for covered_src_word_index in range(fromIndex, toIndex): 
                        new_bit_array[covered_src_word_index] = True
                    if not is_bit_array_valid(new_bit_array, toIndex, DISTORTION_THRESHOLD):
                        continue
                    for phrase in tm[f[fromIndex:toIndex]]:
                        # prune long distance reorderings
                        if abs(fromIndex-h.to_index) > DISTORTION_THRESHOLD:
                            continue
                        # tm prob
                        logprob = h.logprob + phrase.logprob
                        heuristic_logprob = h.heuristic_logprob + phrase.logprob
                        # lm prob
                        lm_state = h.lm_state
                        for word in phrase.english.split():
                            (lm_state, word_logprob) = lm.score(lm_state, word)
                            logprob += word_logprob
                            heuristic_logprob += word_logprob
                        logprob += lm.end(lm_state) if toIndex == len(f) else 0.0
                        heuristic_logprob += lm.end(lm_state) if toIndex == len(f) else 0.0
                        # reordering prob
                        distortion_logprob = -1.0 * DISTORTION_PENALTY ** abs(fromIndex - h.to_index)
                        heuristic_logprob += distortion_logprob
                        new_hypothesis = hypothesis(logprob, heuristic_logprob, lm_state, new_bit_array, toIndex, h, phrase)
                        j = i + toIndex - fromIndex
                        if j >= len(stacks):
                            print 'fatal: whats wrong? i={4}, j={0}, len(stacks)={1}, fromIndex={2}, toIndex={3}'.format(j, len(stacks), fromIndex, toIndex, i)
                            sys.exit(1)
                        if lm_state not in stacks[j] or stacks[j][lm_state].logprob < logprob: # second case is recombination
                            stacks[j][lm_state] = new_hypothesis 

    # the last stack is empty! oh no! 
    if len(stacks[-1]) == 0:
        print "fatal: stack sizes: "
        for stack_index in range(0, len(stacks)):
            print "{0}:{1}".format(stack_index, len(stacks[stack_index]))
        sys.exit()

    # find best translation by looking at the best scoring hypothesis
    # on the last stack
    winner = max(stacks[-1].itervalues(), key=lambda h: h.logprob)
    def extract_english_recursive(h):
        return '' if h.predecessor is None else '%s%s ' % (extract_english_recursive(h.predecessor), h.phrase.english)
    translation = extract_english_recursive(winner)

    # if you use an empty phrase
    if translation.find('MANAAL_WALEED') != -1:
        sys.stderr.write('decoder1: {0} <<{1:.2f}>>, heuristic score {2}\n'.format(translation, winner.logprob, winner.heuristic_logprob))
        winner = baseline_decode(f)
        translation = extract_english_recursive(winner)
        sys.stderr.write('decoder2: {0} <<{1:.2f}>>\n=========\n'.format(translation, winner.logprob))
    else:
        sys.stderr.write('decoder1: {0} <<{1:.2f}>>, heuristic score {2}\n'.format(translation, winner.logprob, winner.heuristic_logprob))
        baselineWinner = baseline_decode(f)
        baselineTranslation = extract_english_recursive(baselineWinner)
        sys.stderr.write('decoder0: {0} <<{1:.2f}>>\n=========\n'.format(baselineTranslation, baselineWinner.logprob))

    # print the translation
    print translation

    if opts.verbose:
        def extract_tm_logprob(h):
            return 0.0 if h.predecessor is None else h.phrase.logprob + extract_tm_logprob(h.predecessor)
        tm_logprob = extract_tm_logprob(winner)
        sys.stderr.write('LM = %f, TM = %f, Total = %f\n' % 
            (winner.logprob - tm_logprob, tm_logprob, winner.logprob))
